export const navigation = [
  {
    label: "Work",
    href: "/platforms",
    roots: ["platforms"],
    summary: "What SozoRock operates",
    items: [
      { label: "SozoRock Global Institute", href: "/platforms/institute", meta: "Insight, publications, and convening" },
      { label: "SozoRock Health", href: "/platforms/health", meta: "Systems for health access" },
      { label: "SozoRock AI Lab", href: "/platforms/ai-lab", meta: "Applied learning for modern work" },
    ],
  },
  {
    label: "Ideas",
    href: "/insights",
    roots: ["publications", "publication", "insights", "events"],
    summary: "Evidence, analysis, and convening",
    items: [
      { label: "Publications", href: "/publications", meta: "Public-interest volumes and permanent records" },
      { label: "Insights", href: "/insights", meta: "Notes, briefings, and field updates" },
      { label: "Events", href: "/events", meta: "Firesides, roundtables, and briefings" },
    ],
  },
  {
    label: "About",
    href: "/about",
    roots: ["about", "leadership", "standards"],
    summary: "Why SozoRock exists",
    items: [
      { label: "Mission", href: "/about#mission", meta: "Institutional purpose" },
      { label: "Leadership", href: "/leadership", meta: "People accountable for the work" },
      { label: "Standards", href: "/standards", meta: "Independence and integrity" },
      { label: "Contact", href: "/about#contact", meta: "Reach the Foundation" },
    ],
  },
];

export const platforms = [
  { slug: "cbcap", name: "CB-CAP", line: "County evidence for local action.", detail: "Public preview: explore county evidence and its sources. Institutional planning access is not available in this release.", href: "https://cbcap.sozorockfoundation.org/", action: "Explore CB-CAP", tone: "cobalt" },
  {
    slug: "institute",
    name: "SozoRock Global Institute",
    line: "Insight, publications, and convening.",
    detail: "Published research examines governance, health access, systems assurance and public-sector capacity, including the realities of rural institutions. Future briefings and roundtables are being developed.",
    href: "/platforms/institute",
    action: "Explore the Institute",
    tone: "cobalt",
  },
  {
    slug: "health",
    name: "SozoRock Health",
    line: "Building the systems that make health access possible.",
    detail: "Community access models, local evidence and digital readiness for communities and institutions, with rural and underserved places among the priorities. Local delivery depends on agreed partner roles and available services.",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    tone: "navy",
  },
  {
    slug: "ai-lab",
    name: "SozoRock AI Lab",
    line: "Applied learning for modern work.",
    detail: "No-cost practical learning with a published participant project: learn, make, check and use reviewed work.",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    tone: "royal",
  },
];

export const publications = [
  {
    slug: "hsa-v1-2026",
    path: "/publication/hsa-v1-2026",
    title: "Health Systems Assurance",
    subtitle: "From compliance to evidence-based digital assurance",
    volume: "Volume 1",
    theme: "Assurance",
    tagline: "Evidence for trustworthy health systems.",
    description: "A public-interest evidence synthesis and policy analysis asking what evidence should support trust when health organizations depend on critical systems, networks, vendors, datasets, and automated tools.",
    metaDescription: "Health Systems Assurance, Volume 1 examines evidence-based digital assurance for trustworthy health systems, vendors, data, and automated tools.",
    cover: "/media/hsa-cover.webp",
    socialImage: "/media/hsa-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "August 2026",
    dateMachine: "2026-08",
    publisher: "The SozoRock Foundation, Inc.",
    publicationPlace: "Albany, New York, USA",
    edition: "First edition",
    evidenceCutoff: "August 12, 2026",
    isbn: "979-8-9936477-3-9",
    language: "English",
    languageCode: "en-US",
    pages: "42 pages",
    fileLabel: "PDF · 4.8 MB",
    accessPath: "/publication/hsa-v1-2026/access",
    accessServiceSlug: "health-systems-assurance-volume-1",
    citation: "Adeyemo, Oluwabiyi. 2026. Health Systems Assurance, Volume 1: From compliance to evidence-based digital assurance. Albany, New York: The SozoRock Foundation, Inc.",
    copyright: "© 2026 The SozoRock Foundation, Inc. All rights reserved. Third-party standards, trademarks, institutional names, and copyrighted source materials remain the property of their respective owners.",
    doi: null,
    external: "https://health.sozorockfoundation.org/publications/health-systems-assurance-volume-1",
    limits: "This volume is not legal advice, a certification or attestation scheme, a clinical standard, or an audit. Its constructs are proposed analytical tools and a research agenda, not validated standards.",
  },
  {
    slug: "rrg-v1-2025",
    doi: "10.65473/rrg-v1-2025",
    publisher: "The SozoRock Foundation, Inc.",
    dateMachine: "2025",
    languageCode: "en-US",
    accessPath: "/publication/rrg-v1-2025/access",
    accessServiceSlug: "rethinking-rural-governance-volume-1",
    path: "/publication/rrg-v1-2025",
    title: "Rethinking Rural Governance Series (RRG)",
    volume: "Volume 1",
    theme: "Governance and systems",
    tagline: "Systems intelligence for local institutions.",
    description: "A governance framework for helping local institutions move from fragmented responses to coordinated decision-making, using rural Delaware County, New York as a reference case.",
    metaDescription: "Rethinking Rural Governance, Volume 1 presents a systems framework for coordinated local decision-making, using rural Delaware County, New York as a reference case.",
    cover: "/media/rrg-cover.webp",
    socialImage: "/media/rrg-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    citation: "Adeyemo, Oluwabiyi. 2025. Rethinking Rural Governance Series (RRG), Volume 1. The SozoRock Foundation, Inc. https://doi.org/10.65473/rrg-v1-2025",
    limits: "Read this as a proposed governance framework. Its use of Delaware County as a reference case does not establish adoption, independent validation or outcomes in that county or elsewhere.",
    external: "https://health.sozorockfoundation.org/publications/rethinking-rural-governance-volume-1",
  },
  {
    slug: "rebs-v1-2025",
    doi: "10.65473/rebs-v1-2025",
    publisher: "The SozoRock Foundation, Inc.",
    dateMachine: "2025",
    languageCode: "en-US",
    accessPath: "/publication/rebs-v1-2025/access",
    accessServiceSlug: "rural-equity-blueprint-volume-1",
    path: "/publication/rebs-v1-2025",
    title: "Rural Equity Blueprint Series (REBS)",
    volume: "Volume 1",
    theme: "Access and equity",
    tagline: "Practical models for access and equity.",
    description: "A practical framework for improving rural health access through accountable local systems, including Health Access Day and related community access models.",
    metaDescription: "Rural Equity Blueprint Series, Volume 1 presents practical models for rural health access, accountable local systems, and community access programs.",
    cover: "/media/rebs-cover.webp",
    socialImage: "/media/rebs-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    citation: "Adeyemo, Oluwabiyi. 2025. Rural Equity Blueprint Series (REBS), Volume 1. The SozoRock Foundation, Inc. https://doi.org/10.65473/rebs-v1-2025",
    limits: "These are proposed access models, not evidence of operating services or measured health outcomes. Local implementation depends on partner agreements, capacity and licensed clinical responsibilities.",
    external: "https://health.sozorockfoundation.org/publications/rural-equity-blueprint-volume-1",
  },
];

export const campaigns = [
  {
    key: "assurance",
    label: "Featured publication",
    title: "Health Systems Assurance",
    copy: "Evidence for trustworthy health systems.",
    detail: "Free verified access · Volume 1",
    href: "/publication/hsa-v1-2026",
    action: "View publication record",
    image: "/media/hsa-cover.webp",
    alt: "Health Systems Assurance, Volume 1 cover",
    kind: "cover",
  },
  {
    key: "health",
    label: "SozoRock Health",
    title: "Care can exist. Access still takes a system.",
    copy: "Connecting community access, place-based intelligence, digital assurance and workforce capacity.",
    detail: "Systems for health access",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    image: "/media/health-access.webp",
    alt: "Two people use a tablet together in a community library",
    kind: "photo",
  },
  {
    key: "ai-lab",
    label: "SozoRock AI Lab",
    title: "AI skills for real life.",
    copy: "Practical learning built around a real task, reviewed output, responsible use, and human judgment.",
    detail: "Learn · Make · Check · Use",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    image: null,
    alt: "",
    signal: "Learn. Make. Check. Use.",
    kind: "type",
  },
];

export const insights = [
  {
    type: "Field update",
    title: "Building the systems that make health access possible",
    summary: "Explore SozoRock Health's work in community access, evidence, digital readiness and workforce capacity.",
    href: "https://health.sozorockfoundation.org/",
    source: "SozoRock Health",
  },
  {
    type: "Systems intelligence",
    title: "Start with a place",
    summary: "A source-traceable approach to geography, evidence dates, comparisons, and limits before drawing a conclusion.",
    href: "https://health.sozorockfoundation.org/explore",
    source: "SozoRock Place Intelligence",
  },
  {
    type: "Applied learning",
    title: "Human judgment at the center",
    summary: "A practical method for learning what tools can do, making something useful, checking the work, and putting a reviewed result into practice.",
    href: "https://ai-lab.sozorockfoundation.org/",
    source: "SozoRock AI Lab",
  },
  {
    type: "Public data demonstration",
    title: "County evidence for local questions",
    summary: "Explore CB-CAP’s public evidence preview, with source dates, definitions and limits. Institutional planning access is not available in this release.",
    href: "https://cbcap.sozorockfoundation.org/",
    source: "SozoRock Health · CB-CAP",
  },
];

export const leaders = [
  {
    name: "Nike Oye, MBA",
    title: "Director of Global Health Partnerships",
    image: "/leadership/nike-oye.webp",
    bio: "Nike Oye coordinates the Foundation’s health partnerships and technical cooperation. She connects community access needs with the organizations and practitioners able to contribute. The focus is on clear partner roles, practical delivery requirements and relationships that support equitable access to care.",
  },
  {
    name: "Anthony Abraham, MSC",
    title: "Director of Global Affairs",
    image: "/leadership/anthony-abraham.jpg",
    bio: "Anthony Abraham leads global affairs and institutional relations. His work addresses cross-border policy questions and cooperation among health, academic and development organizations. He connects local access models with wider institutional conversations, with attention to differences in context and the responsibilities of each organization.",
  },
  {
    name: "Jordan Hare, BSN, RN",
    title: "Director of Health Education",
    image: "/leadership/jordan-hare.webp",
    bio: "Jordan Hare guides health education and community learning. Health literacy, prevention and Health Access Day education are central to her role, connecting evidence with questions people encounter when seeking care. She brings a nursing perspective to education and workforce mentorship; clinical care remains the responsibility of the relevant licensed providers.",
  },
  {
    name: "Dr. Oluwabiyi Adeyemo",
    title: "Director of Strategic Initiatives",
    image: "/leadership/dr-oluwabiyi-adeyemo.webp",
    bio: "Dr. Oluwabiyi Adeyemo leads strategic initiatives across research, policy, technology and program development. He is the author of the Foundation’s publications on health systems assurance, governance and rural equity. He connects that research with community access models, CB-CAP, applied learning and the Foundation’s developing AI & Society work.",
  },
];

export const partnerRoutes = [
  { title: "Examine an access challenge", copy: "Start with a place and a defined access question. Combine public evidence with local knowledge to produce an evidence brief, identify gaps and set a practical next-step agenda, including where rural or underserved conditions matter." },
  { title: "Plan a Health Access Day", copy: "Define the audience, education goals, local host, partner roles, safeguards and follow-up measures before delivery. Clinical work remains with licensed practitioners." },
  { title: "Develop a community Hub", copy: "Assess a library, community or home access model. Define site readiness, digital support, navigation boundaries and provider connections without turning the host into a clinic." },
  { title: "Evaluate a pilot", copy: "Set a focused question, baseline, review plan and practical measures. Document participation, barriers and lessons without presenting a proposed model as proven." },
  { title: "Commission a briefing", copy: "Define a research question, audience and decision. Agree the evidence boundary, contributors, funding disclosures, review process and deliverable before work begins." },
  { title: "Build practical capability", copy: "Develop applied AI or digital-readiness learning around real tasks. Agree the audience, review requirements, safeguards and evidence of learning." },
];
