export const navigation = [
  {
    label: "Work",
    href: "/platforms",
    roots: ["platforms"],
    summary: "What SozoRock operates",
    items: [
      { label: "SozoRock Global Institute", href: "/platforms/institute", meta: "Insight, publications, and convening" },
      { label: "SozoRock Health", href: "/platforms/health", meta: "Access, navigation, and community evidence" },
      { label: "SozoRock AI Lab", href: "/platforms/ai-lab", meta: "Applied learning for modern work" },
    ],
  },
  {
    label: "Ideas",
    href: "/insights",
    roots: ["publications", "publication", "insights", "events"],
    summary: "Evidence, analysis, and convening",
    items: [
      { label: "Publications", href: "/publications", meta: "Public-interest volumes and permanent records" },
      { label: "Insights", href: "/insights", meta: "Notes, briefings, and field updates" },
      { label: "Events", href: "/events", meta: "Firesides, roundtables, and briefings" },
    ],
  },
  {
    label: "About",
    href: "/about",
    roots: ["about", "leadership", "standards"],
    summary: "Why SozoRock exists",
    items: [
      { label: "Mission", href: "/about#mission", meta: "Institutional purpose" },
      { label: "Leadership", href: "/leadership", meta: "People accountable for the work" },
      { label: "Standards", href: "/standards", meta: "Independence and integrity" },
      { label: "Contact", href: "/about#contact", meta: "Reach the Foundation" },
    ],
  },
];

export const platforms = [
  {
    slug: "institute",
    name: "SozoRock Global Institute",
    line: "Insight, publications, and convening.",
    detail: "The Institute develops public-interest publications, briefings, firesides, roundtables, and policy notes across assurance, governance, access, and systems intelligence.",
    href: "/platforms/institute",
    action: "Explore the Institute",
    tone: "cobalt",
  },
  {
    slug: "health",
    name: "SozoRock Health",
    line: "Access, navigation, and community evidence.",
    detail: "A non-clinical layer that helps people move from uncertainty to a practical next step while licensed care stays with licensed providers.",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    tone: "navy",
  },
  {
    slug: "ai-lab",
    name: "SozoRock AI Lab",
    line: "Applied learning for modern work.",
    detail: "No-cost practical learning built around real tasks, human judgment, verification, responsible use, and reviewed implementation.",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    tone: "royal",
  },
];

export const publications = [
  {
    slug: "hsa-v1-2026",
    path: "/publication/hsa-v1-2026",
    title: "Health Systems Assurance",
    subtitle: "From compliance to evidence-based digital assurance",
    volume: "Volume 1",
    theme: "Assurance",
    tagline: "Evidence for trustworthy health systems.",
    description: "A public-interest evidence synthesis and policy analysis asking what evidence should support trust when health organizations depend on critical systems, networks, vendors, datasets, and automated tools.",
    metaDescription: "Health Systems Assurance, Volume 1 examines evidence-based digital assurance for trustworthy health systems, vendors, data, and automated tools.",
    cover: "/media/hsa-cover.webp",
    socialImage: "/media/hsa-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "August 2026",
    dateMachine: "2026-08",
    publisher: "The SozoRock Foundation, Inc.",
    publicationPlace: "Albany, New York, USA",
    edition: "First edition",
    evidenceCutoff: "August 12, 2026",
    isbn: "979-8-9936477-3-9",
    language: "English",
    languageCode: "en-US",
    pages: "42 pages",
    fileLabel: "PDF · 4.8 MB",
    accessPath: "/publication/hsa-v1-2026/access",
    accessServiceSlug: "health-systems-assurance-volume-1",
    citation: "Adeyemo, Oluwabiyi. 2026. Health Systems Assurance, Volume 1: From compliance to evidence-based digital assurance. Albany, New York: The SozoRock Foundation, Inc.",
    copyright: "© 2026 The SozoRock Foundation, Inc. All rights reserved. Third-party standards, trademarks, institutional names, and copyrighted source materials remain the property of their respective owners.",
    doi: null,
    external: "https://health.sozorockfoundation.org/publications/health-systems-assurance-volume-1",
    limits: "This volume is not legal advice, a certification or attestation scheme, a clinical standard, or an audit. Its constructs are proposed analytical tools and a research agenda, not validated standards.",
  },
  {
    slug: "rrg-v1-2025",
    path: "/publication/rrg-v1-2025",
    title: "Rethinking Rural Governance",
    volume: "Volume 1",
    theme: "Governance and systems",
    tagline: "Systems intelligence for local institutions.",
    description: "A governance framework for helping rural institutions move from fragmented responses to coordinated decision-making, using Delaware County, New York as a reference case.",
    metaDescription: "Rethinking Rural Governance, Volume 1 presents a systems framework for coordinated local decision-making, using Delaware County, New York as a reference case.",
    cover: "/media/rrg-cover.webp",
    socialImage: "/media/rrg-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    external: "https://health.sozorockfoundation.org/publications/rethinking-rural-governance-volume-1",
  },
  {
    slug: "rebs-v1-2025",
    path: "/publication/rebs-v1-2025",
    title: "Rural Equity Blueprint Series",
    volume: "Volume 1",
    theme: "Access and equity",
    tagline: "Practical models for access and equity.",
    description: "A practical framework for improving rural health access through accountable local systems, including Health Access Day and related community access models.",
    metaDescription: "Rural Equity Blueprint Series, Volume 1 presents practical models for rural health access, accountable local systems, and community access programs.",
    cover: "/media/rebs-cover.webp",
    socialImage: "/media/rebs-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    external: "https://health.sozorockfoundation.org/publications/rural-equity-blueprint-volume-1",
  },
];

export const campaigns = [
  {
    key: "assurance",
    label: "Featured publication",
    title: "Health Systems Assurance",
    copy: "Evidence for trustworthy health systems.",
    detail: "Free verified access · Volume 1",
    href: "/publication/hsa-v1-2026",
    action: "View publication record",
    image: "/media/hsa-cover.webp",
    alt: "Health Systems Assurance, Volume 1 cover",
    kind: "cover",
  },
  {
    key: "health",
    label: "SozoRock Health",
    title: "A clearer path to care that already exists.",
    copy: "Non-clinical access, navigation, and community evidence while licensed care stays with licensed providers.",
    detail: "Hubs · Health Access Day · Community evidence",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    image: "/media/health-access.webp",
    alt: "Two people use a tablet together in a community library",
    kind: "photo",
  },
  {
    key: "ai-lab",
    label: "SozoRock AI Lab",
    title: "AI skills for real life.",
    copy: "Practical learning built around a real task, reviewed output, responsible use, and human judgment.",
    detail: "Learn · Make · Check · Use",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    image: null,
    alt: "",
    signal: "Learn. Make. Check. Use.",
    kind: "type",
  },
];

export const insights = [
  {
    type: "Field update",
    title: "A clearer path to care that already exists",
    summary: "How a non-clinical access layer can help people begin while providers retain clinical care, records, consent, and follow-up.",
    href: "https://health.sozorockfoundation.org/",
    source: "SozoRock Health",
  },
  {
    type: "Systems intelligence",
    title: "Start with a place",
    summary: "A source-traceable approach to geography, evidence dates, comparisons, and limits before drawing a conclusion.",
    href: "https://health.sozorockfoundation.org/explore",
    source: "SozoRock Place Intelligence",
  },
  {
    type: "Applied learning",
    title: "Human judgment at the center",
    summary: "A practical method for learning what tools can do, making something useful, checking the work, and putting a reviewed result into practice.",
    href: "https://ai-lab.sozorockfoundation.org/",
    source: "SozoRock AI Lab",
  },
  {
    type: "Public data demonstration",
    title: "See the pattern. Test a response. Build a fundable plan.",
    summary: "CB-CAP connects public evidence to local questions, accountable owners, transparent scenarios, and stakeholder-ready briefs.",
    href: "https://cbcap.sozorockfoundation.org/",
    source: "SozoRock Health · CB-CAP",
  },
];

export const leaders = [
  {
    name: "Nike Oye, MBA",
    title: "Director of Global Health Partnerships",
    image: "/leadership/nike-oye.webp",
    bio: "Coordinates strategic alliances with regional and international stakeholders to accelerate innovation in equitable health delivery. Her work focuses on sustaining multilateral partnerships, facilitating technical cooperation, and expanding the Foundation’s reach across emerging and established health ecosystems.",
  },
  {
    name: "Anthony Abraham, MSC",
    title: "Director of Global Affairs",
    image: "/leadership/anthony-abraham.jpg",
    bio: "Leads cross-border policy and institutional relations, building collaborative pathways among health entities, academic networks, and development partners. He structures global alignment so locally grounded models can inform work across different health systems.",
  },
  {
    name: "Jordan Hare, BSN, RN",
    title: "Director of Health Education",
    image: "/leadership/jordan-hare.webp",
    bio: "Guides education and community strategies that advance literacy, prevention, and trust. Her work includes evidence-based engagement models and Health Access Day as a participatory approach to community learning and workforce mentorship.",
  },
  {
    name: "Dr. Oluwabiyi Adeyemo",
    title: "Director of Strategic Initiatives",
    image: "/leadership/dr-oluwabiyi-adeyemo.webp",
    bio: "Designs and leads the Foundation’s strategic architecture across research, policy, technology, and implementation. His work connects the publication portfolio with Health Equity Hubs, Health Access Day, CB-CAP, and applied learning.",
  },
];

export const partnerRoutes = [
  { title: "Request a briefing", copy: "Discuss assurance, governance, access, place intelligence, or applied learning with your team." },
  { title: "Host a Health Access Day", copy: "Explore a locally grounded activation shaped by evidence, partner roles, and licensed scope." },
  { title: "Partner on a Hub", copy: "Consider a library, community, or home access format without turning the host site into a clinic." },
  { title: "Join a fireside", copy: "Convene a focused conversation around a publication, field question, or implementation challenge." },
  { title: "Support a publication", copy: "Help sustain public-interest research, production, dissemination, and convening." },
  { title: "Sponsor applied learning", copy: "Bring practical AI learning to learners, workforce programs, or community organizations." },
];
