export const navigation = [
  {
    label: "Work",
    href: "/platforms",
    roots: ["platforms"],
    summary: "What SozoRock operates",
    items: [
      { label: "SozoRock Global Institute", href: "/platforms/institute", meta: "Research, publications and convening" },
      { label: "SozoRock Health", href: "/platforms/health", meta: "Systems for health access" },
      { label: "SozoRock AI Lab", href: "/platforms/ai-lab", meta: "Applied AI for real work" },
    ],
  },
  {
    label: "Ideas",
    href: "/insights",
    roots: ["publications", "publication", "insights", "events"],
    summary: "Research, analysis and convening",
    items: [
      { label: "Publications", href: "/publications", meta: "Public-interest volumes and permanent records" },
      { label: "Insights", href: "/insights", meta: "Notes, briefings and field updates" },
      { label: "Events", href: "/events", meta: "Firesides, roundtables and briefings" },
    ],
  },
  {
    label: "About",
    href: "/about",
    roots: ["about", "leadership", "standards"],
    summary: "Purpose, leadership and standards",
    items: [
      { label: "Mission", href: "/about#mission", meta: "What the Foundation exists to do" },
      { label: "Leadership", href: "/leadership", meta: "People accountable for the work" },
      { label: "Standards", href: "/standards", meta: "Evidence, independence and integrity" },
      { label: "Contact", href: "/about#contact", meta: "Reach the Foundation" },
    ],
  },
];

export const platforms = [
  {
    slug: "cbcap",
    name: "CB-CAP",
    line: "County evidence for local decisions.",
    detail: "Public preview: county profiles with source dates, definitions and limits. Institution-facing planning work is not open in this release.",
    href: "https://cbcap.sozorockfoundation.org/",
    action: "Explore CB-CAP",
    tone: "cobalt",
  },
  {
    slug: "institute",
    name: "SozoRock Global Institute",
    line: "Research for public decisions.",
    detail: "Published work examines governance, health access, systems assurance and public-sector capacity, including the realities of rural institutions. Briefings and roundtables connect the research to specific questions.",
    href: "/platforms/institute",
    action: "Explore the Institute",
    tone: "cobalt",
  },
  {
    slug: "health",
    name: "SozoRock Health",
    line: "Health access takes a system.",
    detail: "Community access models, place-based evidence, digital readiness and workforce capacity for institutions and communities, including rural and underserved places. Delivery begins with agreed partner roles and available services.",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    tone: "navy",
  },
  {
    slug: "ai-lab",
    name: "SozoRock AI Lab",
    line: "Applied AI for real work.",
    detail: "No-cost practical learning built around a real task, a reviewed output and responsible use. A published participant project shows the method in practice.",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    tone: "royal",
  },
];

export const publications = [
  {
    slug: "hsa-v1-2026",
    path: "/publication/hsa-v1-2026",
    title: "Health Systems Assurance",
    subtitle: "From compliance to evidence-based digital assurance",
    volume: "Volume 1",
    theme: "Assurance",
    tagline: "What evidence should support trust in digital health systems?",
    description: "A public-interest synthesis for leaders responsible for digital health systems: how to connect obligations, risks, operating evidence, exceptions and accountable decisions.",
    metaDescription: "Health Systems Assurance, Volume 1 examines the evidence needed to support trust in digital health systems, vendors, data and automated tools.",
    cover: "/media/hsa-cover.webp",
    socialImage: "/media/hsa-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "August 2026",
    dateMachine: "2026-08",
    publisher: "The SozoRock Foundation, Inc.",
    publicationPlace: "Albany, New York, USA",
    edition: "First edition",
    evidenceCutoff: "August 12, 2026",
    isbn: "979-8-9936477-3-9",
    language: "English",
    languageCode: "en-US",
    pages: "42 pages",
    fileLabel: "PDF · 4.8 MB",
    accessPath: "/publication/hsa-v1-2026/access",
    accessServiceSlug: "health-systems-assurance-volume-1",
    citation: "Adeyemo, Oluwabiyi. 2026. Health Systems Assurance, Volume 1: From compliance to evidence-based digital assurance. Albany, New York: The SozoRock Foundation, Inc.",
    copyright: "© 2026 The SozoRock Foundation, Inc. All rights reserved. Third-party standards, trademarks, institutional names and copyrighted source materials remain the property of their respective owners.",
    doi: null,
    external: "https://health.sozorockfoundation.org/publications/health-systems-assurance-volume-1",
    limits: "This volume is not legal advice, a certification or attestation scheme, a clinical standard or an audit. Its constructs are proposed analytical tools and a research agenda, not validated standards.",
  },
  {
    slug: "rrg-v1-2025",
    doi: "10.65473/rrg-v1-2025",
    publisher: "The SozoRock Foundation, Inc.",
    dateMachine: "2025",
    languageCode: "en-US",
    accessPath: "/publication/rrg-v1-2025/access",
    accessServiceSlug: "rethinking-rural-governance-volume-1",
    path: "/publication/rrg-v1-2025",
    title: "Rethinking Rural Governance Series (RRG)",
    volume: "Volume 1",
    theme: "Governance and systems",
    tagline: "From fragmented response to coordinated public action.",
    description: "A governance framework for local institutions to align decisions, responsibilities and evidence, using rural Delaware County, New York as a reference case.",
    metaDescription: "Rethinking Rural Governance, Volume 1 presents a framework for coordinated local decisions, responsibilities and evidence, using Delaware County as a reference case.",
    cover: "/media/rrg-cover.webp",
    socialImage: "/media/rrg-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    citation: "Adeyemo, Oluwabiyi. 2025. Rethinking Rural Governance Series (RRG), Volume 1. The SozoRock Foundation, Inc. https://doi.org/10.65473/rrg-v1-2025",
    limits: "Read this as a proposed governance framework. Its use of Delaware County as a reference case does not establish adoption, independent validation or outcomes in that county or elsewhere.",
    external: "https://health.sozorockfoundation.org/publications/rethinking-rural-governance-volume-1",
  },
  {
    slug: "rebs-v1-2025",
    doi: "10.65473/rebs-v1-2025",
    publisher: "The SozoRock Foundation, Inc.",
    dateMachine: "2025",
    languageCode: "en-US",
    accessPath: "/publication/rebs-v1-2025/access",
    accessServiceSlug: "rural-equity-blueprint-volume-1",
    path: "/publication/rebs-v1-2025",
    title: "Rural Equity Blueprint Series (REBS)",
    volume: "Volume 1",
    theme: "Access and equity",
    tagline: "A practical framework for local health access.",
    description: "A framework for local health-access planning, including Health Access Day and related community models, with clear distinctions between participation, modeled scenarios and measured outcomes.",
    metaDescription: "Rural Equity Blueprint Series, Volume 1 presents a framework for local health-access planning, Health Access Day and accountable community models.",
    cover: "/media/rebs-cover.webp",
    socialImage: "/media/rebs-social-card.png",
    author: "Dr. Oluwabiyi Adeyemo",
    date: "2025",
    citation: "Adeyemo, Oluwabiyi. 2025. Rural Equity Blueprint Series (REBS), Volume 1. The SozoRock Foundation, Inc. https://doi.org/10.65473/rebs-v1-2025",
    limits: "These are proposed access models, not evidence of operating services or measured health outcomes. Local implementation depends on partner agreements, capacity and licensed clinical responsibilities.",
    external: "https://health.sozorockfoundation.org/publications/rural-equity-blueprint-volume-1",
  },
];

export const campaigns = [
  {
    key: "assurance",
    label: "Featured publication",
    title: "Health Systems Assurance",
    copy: "What evidence should support trust in digital health systems?",
    detail: "Free verified access · Volume 1",
    href: "/publication/hsa-v1-2026",
    action: "View publication record",
    image: "/media/hsa-cover.webp",
    alt: "Health Systems Assurance, Volume 1 cover",
    kind: "cover",
  },
  {
    key: "health",
    label: "SozoRock Health",
    title: "Care can exist. Access still takes a system.",
    copy: "Community access, place-based evidence, digital readiness and workforce capacity.",
    detail: "Systems for health access",
    href: "/platforms/health",
    action: "Explore SozoRock Health",
    image: "/media/health-access.webp",
    alt: "Two people use a tablet together in a community setting",
    kind: "photo",
  },
  {
    key: "ai-lab",
    label: "SozoRock AI Lab",
    title: "Applied AI for real work.",
    copy: "Task-based learning, reviewed output, responsible use and human judgment.",
    detail: "Learn · Make · Check · Use",
    href: "/platforms/ai-lab",
    action: "Explore the AI Lab",
    image: null,
    alt: "",
    signal: "Learn. Make. Check. Use.",
    kind: "type",
  },
];

export const insights = [
  {
    type: "Field update",
    title: "Health access takes a system",
    summary: "See how community access, evidence, digital readiness and workforce capacity fit together.",
    href: "https://health.sozorockfoundation.org/",
    source: "SozoRock Health",
  },
  {
    type: "Systems intelligence",
    title: "Start with a place",
    summary: "Examine geography, source dates, definitions, comparisons and limits before drawing a conclusion.",
    href: "https://health.sozorockfoundation.org/explore",
    source: "SozoRock Place Intelligence",
  },
  {
    type: "Applied learning",
    title: "Human judgment stays in the work",
    summary: "Learn what a tool can do, build something useful, verify it and put the reviewed result into practice.",
    href: "https://ai-lab.sozorockfoundation.org/",
    source: "SozoRock AI Lab",
  },
  {
    type: "Public data demonstration",
    title: "County evidence, with sources and limits",
    summary: "Explore CB-CAP’s public evidence preview. Institution-facing planning access is not open in this release.",
    href: "https://cbcap.sozorockfoundation.org/",
    source: "SozoRock Health · CB-CAP",
  },
];

export const leaders = [
  {
    name: "Nike Oye, MBA",
    title: "Director of Global Health Partnerships",
    image: "/leadership/nike-oye.webp",
    bio: "Nike Oye leads institutional relationships for health-access work. Her role is to clarify partner responsibilities, delivery requirements and the contribution each organization can make.",
  },
  {
    name: "Anthony Abraham, MSC",
    title: "Director of Global Affairs",
    image: "/leadership/anthony-abraham.jpg",
    bio: "Anthony Abraham leads global affairs and cross-border institutional relations. He focuses on cooperation among health, academic and development organizations without obscuring differences in mandate, jurisdiction or accountability.",
  },
  {
    name: "Jordan Hare, BSN, RN",
    title: "Director of Health Education",
    image: "/leadership/jordan-hare.webp",
    bio: "Jordan Hare leads health education and community learning. Her work covers health literacy, prevention, Health Access Day education and workforce mentorship; clinical care remains with licensed providers.",
  },
  {
    name: "Dr. Oluwabiyi Adeyemo",
    title: "Director of Strategic Initiatives",
    image: "/leadership/dr-oluwabiyi-adeyemo.webp",
    bio: "Dr. Oluwabiyi Adeyemo leads research, policy, technology and program development. He is the author of the Foundation’s publications on health systems assurance, governance and rural equity, and connects that work with community access, applied learning and AI & Society.",
  },
];

export const partnerRoutes = [
  { title: "Define an access challenge", copy: "Start with a place, an audience and a decision. The engagement produces a source-led brief, a gap register and a practical next-step agenda, including where rural or underserved conditions matter." },
  { title: "Plan a Health Access Day", copy: "Set the audience, education goals, local host, partner roles, safeguards and follow-up measures. The output is a delivery brief with responsibilities and boundaries; clinical work remains with licensed practitioners." },
  { title: "Assess a community access site", copy: "Examine a library, community or home-based model. The assessment covers site readiness, digital support, navigation boundaries, provider connections and the roles required for delivery." },
  { title: "Evaluate a pilot", copy: "Agree a focused question, baseline, measures and review schedule. The work documents participation, barriers, results and limits without presenting a proposed model as proven." },
  { title: "Commission a briefing", copy: "Define the decision, audience and evidence boundary. Agree contributors, funding disclosure and review before delivery of a concise brief and presentation." },
  { title: "Build applied capability", copy: "Develop task-based AI or digital-readiness learning with review criteria, safeguards and an assessed work product—not training measured only by attendance." },
];
